-- require("websocket")
-- require("tmr")

-- local wsclient = websocket.createClient()
-- local function connect()
--     wsclient:connect('ws://121.40.165.18:8800')
-- end
-- wsclient:on("connection", function(ws, s)
--     print('got ws connection', s)
-- end)
-- wsclient:on("receive", function(_, msg, opcode)
--     print('got message:', msg, opcode) -- opcode is 1 for text message, 2 for binary
-- end)
-- wsclient:on("close", function(_, status)
--     print('connection closed', status)
--     --   ws = nil -- required to Lua gc the websocket client

--     local mytimer = tmr.create()
--     mytimer:register(2000, tmr.ALARM_SINGLE, function(t)
--         connect()
--         mytimer:unregister()
--         mytimer = nil
--     end)
--     mytimer:start()
-- end)
-- connect()
-- -- wsclient:close()
-- -- wsclient = nil
-- return wsclient
